OneUptime/oneuptime

.github/workflows/compile.common.yaml

add action to compile common

---

.github/workflows/docker-build.haraka.yaml
ProbeAPI/.env
docker-compose.ci.yml

Feature: haraka docker build workflow #24

---

.github/workflows/compile.common-server.yaml
.github/workflows/compile.home.yaml
.github/workflows/compile.licensing.yaml
.github/workflows/compile.mail.yaml
.github/workflows/compile.probe-api.yaml
CommonServer/Services/DatabaseService.ts
CommonServer/Services/RealTimeService.ts
Licensing/package-lock.json
Licensing/package.json
Licensing/src/Api/License.ts
Licensing/src/Services/LicenseService.ts
Licensing/src/Utils/WebToken.ts
Mail/API/Mail.ts
Mail/Index.ts
ProbeAPI/API/Probe.ts
ProbeAPI/Index.ts

Feature: Compile GitHub actions job for /Home, /ProbeAPI, /CommonServer, and /Licensing

---

CONTRIBUTING.md

Add CONTRIBUTING.md template

---

Common/Tests/Slug.test.ts
Common/Utils/Slug.ts

Pull request for issue #34 
Close #34

Add tests for Common/Util/Slug

---

.github/pull_request_template.md

Pull request template that shows user guidelines before submitting a pull request.
closes #39

chore(github actions): add pull request template

---

LICENSE

The changed the license from APACHE to MIT
**references**
https://choosealicense.com/licenses/mit/

 update license #28

---

.github/workflows/compile.helmchart.yaml
HelmChart/index.ts

Chore: add compile job for HelmChart

---

.eslintrc.json
CommonServer/Middleware/ProbeAuthorization.ts
CommonServer/Middleware/UserAuthorization.ts
CommonServer/Services/DatabaseService.ts
DashboardAPI/api/PerformanceTrackerMetric.ts
DashboardAPI/workers/main.ts
Scripts/Index.ts

Await dangling promises

---

.eslintrc.json

```
const foo: { bar: number } | null = null;
const bar = foo!!!.bar;
```
```
function foo(bar?: { n: number }) {
return bar?.n;
}
```
closes #88

Add linting for non-null-assertion

---

.eslintrc.json
Common/Types/API/Headers.ts
Common/Types/JSON.ts
CommonServer/Types/DB/DeleteBy.ts
CommonServer/Types/DB/UpdateBy.ts
CommonUI/src/PayloadTypes/ApiBasePayloadType.ts
CommonUI/src/PayloadTypes/ErrorPayloadType.ts
CommonUI/src/PayloadTypes/ModalPayloadType.ts
CommonUI/src/Types/ActionPayload.ts
CommonUI/src/Types/HtmlEvents.ts
StatusPage/src/Components/basic/Socket.ts

86 disallow the declaration of empty interfaces

---

Common/Tests/Types/Email/Email.test.ts
Common/Types/Email.ts

Add tests for Email

---

Common/Tests/Types/Exception/ApiException.test.ts
Common/Tests/Types/Exception/BadDataException.test.ts
Common/Tests/Types/Exception/BadOperationException.test.ts
Common/Tests/Types/Exception/BadRequestException.test.ts
Common/Tests/Types/Exception/DatabaseNotConnectedException.test.ts
Common/Tests/Types/Exception/Exception.test.ts
Common/Tests/Types/Exception/NotImplementedException.test.ts
Common/Types/Exception/Exception.ts

Add tests for exceptions

---

Accounts/src/App.scss
Accounts/src/App.tsx
Accounts/src/Footer.tsx
Accounts/src/Pages/ForgotPassword.tsx
Accounts/src/Pages/Login.tsx
Accounts/src/Pages/Register.tsx
Accounts/src/Pages/SsoLogin.tsx
CommonUI/src/Components/Forms/BasicForm.tsx
CommonUI/src/Components/Forms/BasicModelForm.tsx

Add styling for SSO and forgot password page

---

Accounts/src/App.scss
Accounts/src/Pages/ForgotPassword.tsx
Accounts/src/Pages/Login.tsx
Accounts/src/Pages/SsoLogin.tsx
Accounts/src/index.tsx
Common/Tests/Types/API/Route.test.ts
Common/Types/API/Route.ts
CommonUI/src/Components/Forms/BasicForm.tsx
CommonUI/src/Components/Forms/Types/Field.ts

Add validation to required fields

---

Accounts/src/App.scss
Accounts/src/App.tsx
Accounts/src/Pages/ForgotPassword.tsx
Accounts/src/Pages/Login.tsx
Accounts/src/Pages/Register.tsx
Accounts/src/Pages/SsoLogin.tsx
Common/Models/BaseModel.ts
CommonUI/src/Components/Forms/BasicForm.tsx
CommonUI/src/Components/Forms/BasicModelForm.tsx

style register page

---

Home/package-lock.json
Home/package.json
docker-compose.ci.yml
docker-compose.dev.yml
docker-compose.yml

fix home build

---

CommonUI/src/Components/Dashboard/TopBar/NavLink/NavContainer.tsx
CommonUI/src/Components/Dashboard/TopBar/NavLink/NavDropDown/NavDropDown.scss
CommonUI/src/Components/Dashboard/TopBar/NavLink/NavDropDown/NavDropDown.tsx
CommonUI/src/Components/Dashboard/TopBar/NavLink/NavDropDown/NavDropDownItem.tsx
CommonUI/src/Components/Dashboard/TopBar/NavLink/NavLink.tsx
CommonUI/src/Components/Dashboard/TopBar/TopBar.scss
CommonUI/src/Components/Dashboard/TopBar/TopBar.tsx
Dashboard/src/App.tsx
Dashboard/src/Components/Navigations/Dropdown.tsx

Style dropdown

---

CommonUI/src/Components/Dashboard/Container/Breadcrumb/Breadcrumb.scss
CommonUI/src/Components/Dashboard/Container/Breadcrumb/Breadcrumb.tsx
CommonUI/src/Components/Dashboard/Container/Container.scss
CommonUI/src/Components/Dashboard/Sidebar/Sidebar.scss
CommonUI/src/Components/Dashboard/TopBar/TopBar.scss
Dashboard/src/Pages/Monitors.tsx

closes #145 
(if appropriate):

Style Breadcrumbs

---

Accounts/src/Pages/Register.tsx
CommonUI/src/Components/Forms/BasicForm.tsx
CommonUI/src/Components/Forms/BasicModelForm.tsx
CommonUI/src/Components/Forms/Types/Field.ts

addOnValidate to form.

---

CommonUI/src/Components/Basic/Modal/BasicModal.tsx
CommonUI/src/Components/Basic/Modal/ConfirmTextModal.tsx
CommonUI/src/Components/Basic/Modal/Modal.scss
CommonUI/src/Components/Basic/Modal/ModalIcon.ts
Dashboard/src/Pages/Monitors.tsx

Style Modal

---

Common/Tests/Types/HashedString.test.ts

add more test

---

.husky/pre-commit
Common/Tests/TestingUtils/Faker.ts
Common/Tests/Types/Phone.test.ts
Common/Tests/Types/Port.test.ts
Common/Types/Phone.ts
Common/package.json

🧪 TEST: Port and Phone class

---

Common/Tests/Types/Company/CompanySize.test.ts
Common/Tests/Types/Company/JobRole.test.ts

Tests for Common/Types/Company
I wrote tests for Common/Types/Company that includes JobRoles.ts and CompanySize.ts

Write tests for  common/types/company

---

Common/Tests/Types/Color.test.ts

Writing tests for Common/Types/Color

Writing tests for Common/Types/Color

---

.github/workflows/test.commonui.yaml
Common/package-lock.json
Common/package.json
CommonUI/jest.config.json
CommonUI/package-lock.json
CommonUI/package.json
CommonUI/src/Tests/Breadcrumbs.test.tsx
CommonUI/tsconfig.json
package-lock.json
package.json

Jest integration

---

Common/Tests/Types/Name.test.ts
Common/Types/Name.ts

Added Name.test.ts

---

CommonServer/API/BaseAPI.ts
CommonServer/Services/ApiKeyService.ts
CommonServer/Services/DatabaseService.ts
CommonServer/Services/LabelService.ts
CommonServer/Services/ProjectService.ts
CommonServer/Services/TeamMemberService.ts
CommonServer/Services/TeamPermissionService.ts
CommonServer/Services/TeamService.ts
CommonUI/src/Components/ModelTable/ModelTable.tsx
CommonUI/src/Utils/ModelAPI/ModelAPI.ts
Dashboard/src/App.tsx
Dashboard/src/Components/Header/Header.tsx
Dashboard/src/Components/Header/ProjectInvitationsModal.tsx
Dashboard/src/Components/MasterPage/MasterPage.tsx
Nginx/default.conf

Refactor UI

---

CommonUI/src/Components/Toast/Toast.tsx
CommonUI/src/Tests/Toast.test.tsx
CommonUI/tsconfig.json

Toast.test.tsx

---

CommonUI/src/Components/Pill/Pill.tsx
CommonUI/src/Tests/Pill.test.tsx

Pill.test.tsx

---

Docs/run.md
docker-compose.yml

corrected typos 
correct  some writing mistakes

fix a couple  typos

---

CommonUI/src/Components/Alerts/Alert.tsx
CommonUI/src/Tests/alert.test.tsx

tests for CommonUI/src/Components/Alerts/Alert.tsx #238

Tests for CommonUI/src/Components/Alerts/Alert.tsx #238

---

.github/workflows/test.probe.yaml
Probe/Tests/Utils/PingMonitor.test.ts
Probe/Tests/index.test.ts
Probe/Utils/PingMonitor.ts

- implement the ping monitor
Implement the ping using tcp sockets
closes #167

Implement Ping Monitor

---

CommonServer/API/BaseAPI.ts
CommonServer/API/BillingInvoiceAPI.ts
CommonServer/API/BillingPaymentMethodAPI.ts
CommonServer/API/StatusPageAPI.ts
CommonServer/API/StatusPageSubscriberAPI.ts
DashboardAPI/Index.ts
File/API/File.ts
File/Index.ts
Home/views/ccpa.ejs
Home/views/contact.ejs
Home/views/dmca.ejs
Home/views/enterprise-overview.ejs
Home/views/footer.ejs
Home/views/nav.ejs
Home/views/privacy.ejs
Home/views/sla.ejs
Home/views/subprocessors.ejs
Home/views/terms.ejs
Nginx/default.tpl.conf
Workers/Index.ts

fix routes

---

docker-compose.tpl.yml

fix restarrt

---

preinstall.sh

fix preinstall

---

Dashboard/src/App.tsx
Dashboard/src/Pages/Home/Home.tsx

Fix Home Link Redirect
Fix Home link so it redirects users to welcome page if user has no projects
Closes #352
Signed-off-by: jmeridth <jmeridth@gmail.com>

fix(link): Fix Home Link redirect

---

README.md

Typo fix README.md

---

.github/workflows/test.common.yaml
Common/Tests/Types/API/ErrorResponse.test.ts
Common/Tests/Types/API/Response.test.ts
Common/Tests/Types/Alerts/AlertEventType.test.ts
Common/Tests/Types/Alerts/AlertType.test.ts
Common/Tests/Types/ApplicationLog/ApplicationLogType.test.ts
Common/Tests/Types/Code/CodeType.test.ts
Common/Tests/Types/Database/LimitMax.test.ts
Common/Tests/Types/Email/Email.test.ts
Common/Tests/Types/Phone.test.ts
Common/Tests/Types/Port.test.ts
Common/Types/Alerts/AlertEventType.ts
Common/Types/ApplicationLog/ApplicationLogType.ts
Common/Types/Code/CodeType.ts

Add test for the alerts

---

Common/Types/Incident/IncidentCustomFields.ts
Common/Types/Workflow/ComponentID.ts
Common/Types/Workflow/Components/Manual.ts
CommonServer/Infrastructure/Queue.ts
CommonServer/Services/WorkflowService.ts
CommonServer/Types/Workflow/ComponentCode.ts
CommonServer/Types/Workflow/Components/Index.ts
CommonServer/Types/Workflow/Components/Manual.ts
CommonServer/Types/Workflow/Components/OnTriggerBaseModel.ts
CommonServer/Types/Workflow/Components/Schedule.ts
CommonServer/Types/Workflow/Components/Webhook.ts
CommonServer/Types/Workflow/TriggerCode.ts
CommonServer/Types/Workflow/Workflow.ts
CommonUI/src/Components/Workflow/Utils.ts
Model/Models/IncidentCustomField.ts
Model/Models/MonitorCustomField.ts
Model/Models/ScheduledMaintenanceCustomField.ts
Model/Models/StatusPageCustomField.ts
Model/Models/Workflow.ts
Model/Models/WorkflowVariable.ts
Workflow/API/ComponentCode.ts
Workflow/API/Workflow.ts
Workflow/Index.ts
Workflow/Services/QueueWorkflow.ts
Workflow/Services/RunWorkflow.ts

Workflow project

---

Workers/Jobs/StatusPageCerts/StausPageCerts.ts
Workers/Utils/Greenlock/Manager.ts
Workers/Utils/Greenlock/Store.ts

add logs to greenlock store

---

Home/views/legal.ejs
Home/views/nav.ejs

[Before](https://i.imgur.com/slMSJf8.png)
[After](https://i.imgur.com/PGkHSPp.png)

Fix contact cards in /support overlapping the navigation dropdown

---

Common/Tests/Types/Database/CompareBase.test.ts
Common/Tests/Types/Database/NotEqual.test.ts

Written test for some database files

Test Cases for Some Database Files

---

CommonUI/src/Components/RadioButtons/RadioButtons.tsx
CommonUI/src/Components/Toggle/Toggle.tsx
CommonUI/src/Tests/Components/Dropdown.test.tsx
CommonUI/src/Tests/Components/RadioButtons.test.tsx
CommonUI/src/Tests/Components/TextArea.test.tsx
CommonUI/src/Tests/Components/Toggle.test.tsx

Add basic input components tests

---

Common/Tests/Utils/API.test.ts

Closes #33
N/A
---
These was previously part of #396 but I created a new branch. There seems to be no way to switch the base branch after force-pushing to a base branch that's in-sync with the upstream.

Add tests for Common/Utils/API

---

Common/Tests/Types/BrandColors.test.ts

Tests for Brand Colors

---

CommonUI/src/Tests/Components/Template/Template.test.tsx

Test for CommonUI/Template

---

CommonUI/src/Tests/Components/EmptyState/EmptyState.test.tsx

Test Cases for CommonUI/EmptyState

---

CommonUI/src/Components/ErrorMessage/ErrorMessage.tsx
CommonUI/src/Tests/Components/OrderedStatesList.test.tsx

Test Cases for CommonUI/OrderedStatesList

---

CommonUI/src/Components/ErrorMessage/ErrorMessage.tsx
CommonUI/src/Tests/Components/Item.test.tsx
CommonUI/src/Tests/Components/OrderedStatesList.test.tsx

Test Cases for Common UI/OrderedStatesList/Items

---

Common/Tests/Types/Billing/SubscriptionPlan.test.ts

Test cases for Common/Billing

---

CommonUI/src/Tests/Components/Card.test.tsx

- Added unit tests for file `CommonUI/src/Components/Card/Card.tsx` 
- Added unit tests file `CommonUI/src/Components/Card/Card.tsx`
- The unit tests file is created inside `CommonUI/src/Tests/Components` directory 
closes https://github.com/OneUptime/oneuptime/issues/468

test: added unit tests for Card Component

---

CommonServer/Tests/Middleware/ClusterKeyAuthorization.test.ts
CommonServer/Tests/Middleware/ProjectAuthorization.test.ts

- added unit tests for CommonServer/Middleware
- I added unit tests for files inside CommonServer/Middleware directory.
- The added unit test files are inside CommonServer/Tests/Middleware
closes https://github.com/OneUptime/oneuptime/issues/464

test: added unit tests for CommonServer/Middleware

---

CommonServer/Middleware/UserAuthorization.ts
CommonServer/Tests/Middleware/UserAuthorization.test.ts

- added unit test for file `CommonServer/Middleware/UserAuthorization.ts`
- I added unit tests for file `UserAuthorization.ts` inside directory `CommonServer/Middleware directory`.
- The added unit test file is inside `CommonServer/Tests/Middleware`
- I refactored function `getUserMiddleware` inside `UserAuthorization.ts`. Broken the function down into sub-functions to improve its readability and testability.
closes https://github.com/OneUptime/oneuptime/issues/466

test: added unit test for file CommonServer/Middleware/UserAuthorization

---

StatusPage/src/App.tsx
StatusPage/src/Components/MasterPage/MasterPage.tsx
StatusPage/src/Pages/Accounts/ForgotPassword.tsx
StatusPage/src/Pages/Accounts/Login.tsx
StatusPage/src/Pages/Accounts/Logout.tsx
StatusPage/src/Pages/Accounts/ResetPassword.tsx
StatusPage/src/Pages/Accounts/SSO.tsx
StatusPage/src/Pages/Announcement/Detail.tsx
StatusPage/src/Pages/Announcement/List.tsx
StatusPage/src/Pages/Incidents/Detail.tsx
StatusPage/src/Pages/Incidents/List.tsx
StatusPage/src/Pages/Overview/Overview.tsx
StatusPage/src/Pages/PageComponentProps.ts
StatusPage/src/Pages/ScheduledEvent/Detail.tsx
StatusPage/src/Pages/ScheduledEvent/List.tsx
StatusPage/src/Pages/Subscribe/EmailSubscribe.tsx
StatusPage/src/Utils/StatusPage.ts

Staus Page redirection fix

---

Common/Types/Workflow/Component.ts
Common/Types/Workflow/Components/BaseModel.ts
CommonServer/Services/DatabaseService.ts
CommonServer/Types/Workflow/Components/BaseModel/OnTriggerBaseModel.ts
CommonServer/Types/Workflow/TriggerCode.ts
CommonUI/src/Components/Workflow/RunModal.tsx
CommonUI/src/Components/Workflow/Utils.ts
Workflow/Services/RunWorkflow.ts

add select clause to trigger

---

CommonServer/Services/DatabaseService.ts

fix createdat

---

Common/Types/OnCallDutyPolicy/OnCalDutyExecutionLogTimelineStatus.ts
Common/Types/OnCallDutyPolicy/OnCallDutyPolicyStatus.ts
Common/Types/UserNotification/UserNotificationExecutionStatus.ts
Common/Types/Workflow/WorkflowStatus.ts
CommonServer/Services/OnCallDutyPolicyEscalationRuleService.ts
CommonServer/Services/OnCallDutyPolicyExecutionLogService.ts
CommonServer/Services/UserNotificationLogService.ts
Dashboard/src/Components/OnCallPolicy/ExecutionLogs/ExecutionLogsTable.tsx
Dashboard/src/Components/OnCallPolicy/ExecutionLogs/ExecutionLogsTimelineTable.tsx
Dashboard/src/Pages/UserSettings/NotificationLogs.tsx
Workers/Jobs/OnCallDutyPolicyExecutionLog/ExecutePendingExecutions.ts
Workers/Jobs/UserNotificationLog/ExecutePendingExecutions.ts

On call fixes

---

Dashboard/src/Components/OnCallPolicy/ExecutionLogs/ExecutionLogsTable.tsx
Model/Models/ShortLink.ts

fix shortlink logs

---

CommonServer/test-setup.sh
Home/views/features-table.ejs

fix test script

---

.github/workflows/test.common-server.yaml

add read env var

---

Dashboard/src/Pages/UserSettings/SideMenu.tsx
Home/views/about.ejs
Home/views/features-table.ejs
Home/views/index.ejs
Home/views/support.ejs
Home/views/workflows.ejs
README.md

Spelling, grammar, punctuation fixes

Spelling corrections

---

Dashboard/src/Pages/Settings/Domains.tsx

Fix misspelled "propogate"
Fixed a single misspelled word that was bugging me lol

Fix misspelled "propogate"

---

ApiReference/Index.ts
ApiReference/Service/Model.ts
ApiReference/Utils/Resources.ts
ApiReference/views/main/introduction.ejs
Dashboard/src/Pages/StatusPages/View/Resources.tsx
HelmChart/public/oneuptime/templates/api-docs.yaml
HelmChart/public/oneuptime/templates/exposed-init-script.yaml
HelmChart/public/oneuptime/templates/helm-chart.yaml
HelmChart/public/oneuptime/templates/home.yaml
HelmChart/public/oneuptime/templates/licensing.yaml
Home/views/about.ejs
Home/views/comparision-chart.ejs
Home/views/footer.ejs
Home/views/index.ejs
Home/views/monitoring.ejs
Home/views/pricing-compare.ejs
Home/views/status-page.ejs
README.md
StatusPage/src/Pages/Overview/Overview.tsx

More copy edits. Note that I did rename one function and one variable as well.

Copy edits

---

Common/Types/Permission.ts
Dashboard/src/Components/Header/ProjectPicker.tsx
Dashboard/src/Components/Header/Upgrade.tsx
Dashboard/src/Components/NavBar/NavBar.tsx
Dashboard/src/Pages/Global/UserProfile/Index.tsx
Home/views/nav.ejs

(this is why I'm no fun at parties)

More copy edits

---

.github/workflows/release.yml
.github/workflows/test-release.yml

This PR adds support for pushing to ghcr.io as an alternative mirror to docker hub. See #554 for information.
#554

Add support for ghcr.io as a mirror

---

.github/workflows/release.yml

Thirdtimesthecharm

---

.github/workflows/release.yml

Outdated Docs Will Be My Downfall

---

.github/workflows/release.yml

value needs to be set with pattern being version

---

Common/Types/Monitor/MonitorCriteriaInstance.ts
Dashboard/src/Components/Form/Monitor/MonitorCriteriaInstance.tsx
Dashboard/src/Components/Form/Monitor/MonitorStep.tsx
Dashboard/src/Components/Form/Monitor/MonitorSteps.tsx
Dashboard/src/Components/Incident/IncidentsTable.tsx
Dashboard/src/Components/Monitor/MonitorSteps/MonitorCriteriaInstance.tsx
Dashboard/src/Components/Monitor/MonitorSteps/MonitorStep.tsx
Dashboard/src/Components/Monitor/MonitorTable.tsx
Dashboard/src/Components/ScheduledMaintenance/ScheduledMaintenanceTable.tsx
Dashboard/src/Pages/OnCallDuty/OnCallDutyPolicy/Escalation.tsx
Dashboard/src/Pages/StatusPages/StatusPages.tsx
Model/Models/Monitor.ts

Monitor copyedits

---

CommonServer/Services/ProjectService.ts

fix: addDefaultNotifictionRuleForUser 

---

Dashboard/src/Pages/StatusPages/View/SideMenu.tsx

Announcements on the status page was misspelled.
None

chore: fix sidebar misspelling

---

Accounts/public/index.html
Dashboard/public/index.html
StatusPage/public/index.html

removing default react  page descriptions

Fix: page description

---

README.md

This pull request updates the README.md file with the following changes:
- Added a subtitle that summarizes what OneUptime does: "The Complete Open-Source Observability Platform"
- Rewrote the introduction paragraph to highlight the benefits and features of OneUptime
- Replaced the bullet list of what OneUptime does with a table that compares OneUptime with other tools
- Added a "Coming soon" label to the features that are not yet available
- Added a section on how to get started for free with OneUptime Cloud
- Added a section on how to choose your system requirements based on your usage and budget
- Added a section on the prerequisites for single-server deployment
- Fixed some typos and formatting issues
The updated README.md file is more informative, comprehensive, and engaging for …

Update README.md with new features, content, and deployment instructions

---

configure.sh

fix configure.sh local: can only be used in a function
- [ X] Have you lint your code locally before submission?

fix DISTRIB

---

Common/Types/Email.ts
CommonUI/src/Components/Forms/BasicForm.tsx
CommonUI/src/Components/Forms/Fields/FormField.tsx
CommonUI/src/Components/ModelTable/ModelTable.tsx
CommonUI/src/Utils/Dropdown.ts
Dashboard/src/Components/Incident/IncidentsTable.tsx
Model/Models/IncidentTemplate.ts

add incident templates

---

CommonUI/src/Components/Dropdown/Dropdown.tsx
CommonUI/src/Components/Navbar/NavBarMenu.tsx
Dashboard/src/Pages/Settings/IncidentTemplates.tsx
Dashboard/src/Pages/Settings/IncidentTemplatesView.tsx
Model/Models/IncidentTemplate.ts

Clickhouse client

---

Common/Types/Workflow/Component.ts
Common/Types/Workflow/Components/Slack.ts
CommonServer/Services/UserCallService.ts
CommonServer/Services/UserSmsService.ts
CommonServer/Types/Workflow/Components/Slack/SendMessageToChannel.ts
CommonUI/src/Components/Workflow/Utils.ts

add markdown to slack.

---

Accounts/src/Pages/Register.tsx
Common/Types/Date.ts
Common/Types/Exception/ExceptionCode.ts
Common/Types/Exception/TenantNotFoundException.ts
CommonServer/API/ResellerPlanAPI.ts
CommonServer/Middleware/BearerTokenAuthorization.ts
CommonServer/Middleware/UserAuthorization.ts
CommonServer/Services/BillingService.ts
CommonServer/Services/Index.ts
CommonServer/Services/ProjectService.ts
CommonServer/Services/PromoCodeService.ts
CommonServer/Services/ResellerPlanService.ts
CommonServer/Services/ResellerService.ts
CommonServer/Utils/Express.ts
CommonServer/Utils/JsonWebToken.ts
CommonServer/Utils/Response.ts
CommonUI/src/Components/Input/Input.tsx
CommonUI/src/Utils/API/API.ts
Dashboard/src/Components/Header/ProjectPicker.tsx
DashboardAPI/Index.ts
Identity/API/Reseller.ts
Identity/Index.ts
Model/Models/Index.ts
Model/Models/Project.ts
Model/Models/PromoCode.ts
Model/Models/Reseller.ts
Model/Models/ResellerPlan.ts

add reseller models

---

CommonServer/Services/ProjectService.ts
Dashboard/src/Pages/Settings/ScheduledMaintenanceState.tsx
Model/Models/ScheduledMaintenanceState.ts
Workers/DataMigrations/AddEndedState.ts
Workers/DataMigrations/Index.ts
Workers/Index.ts
Workers/Jobs/ScheduledMaintenance/ChangeStateToEnded.ts

Add end state to events

---

Accounts/Dockerfile.tpl
AdminDashboard/Dockerfile.tpl
ApiReference/Dockerfile.tpl
Common/Types/Monitor/CriteriaFilter.ts
CommonServer/Types/Workflow/Components/JavaScript.ts
CommonServer/Utils/Probe/ProbeMonitorResponse.ts
CommonServer/Utils/VM.ts
Dashboard/Dockerfile.tpl
Dashboard/src/Components/Form/Monitor/CriteriaFilter.tsx
Dashboard/src/Components/Monitor/MonitorSteps/CriteriaFilter.tsx
DashboardAPI/Dockerfile.tpl
Docs/Monitor/JavaScriptExpression.md
File/Dockerfile.tpl
Haraka/Dockerfile.tpl
Home/Dockerfile.tpl
Identity/Dockerfile.tpl
Integration/Dockerfile.tpl
Licensing/Dockerfile.tpl
LinkShortener/Dockerfile.tpl
Notification/Dockerfile.tpl
Probe/Dockerfile.tpl
Probe/Utils/Monitors/Monitor.ts
ProbeAPI/Dockerfile.tpl
Realtime/Dockerfile.tpl
StatusPage/Dockerfile.tpl
TestServer/Dockerfile.tpl
Tests/Dockerfile.tpl
Workers/Dockerfile.tpl
Workflow/Dockerfile.tpl
Workflow/Services/RunWorkflow.ts

Parse json on monitors

---

CommonUI/src/Tests/Components/ColorViewer.test.tsx

Test for the color viewer component
This PR creates test suites for the `ColorViewer` component, testing the renders on different conditions, clicks, etc
#799

Create test for the color viewer component

---

CommonUI/src/Tests/Components/404.test.tsx

Test for 404 page
This PR add extensive testing for the 404 page
#799

Add test file for 404 page

---

CommonUI/src/Tests/Components/MasterPage.test.tsx
CommonUI/src/Tests/Components/TopSection.test.tsx

Test Cases
- Created unit tests for MasterPage & TopSection component to ensure correct rendering
- Covered various scenarios, including different props, states and classNames

Adds test cases for MasterPage & TopSection

---

Dashboard/src/Components/Form/Monitor/CriteriaFilter.tsx

Fix typo in "expressions"
This just fixes a typo

Fix typo in "expressions"

---

Common/Tests/Utils/API.test.ts
Common/Tests/Utils/Analytics.test.ts
Common/Tests/Utils/CronTime.test.ts
Common/Tests/Utils/Faker.test.ts
Common/Tests/Utils/Slug.test.ts

Test cases for Common/Utils
Common/Utils are 100% test covered now
Before: 
After:

Adds Test cases for Common/Utils to make 100% coverage

---

CommonUI/package-lock.json
CommonUI/package.json
CommonUI/src/Components/ErrorBoundary.tsx
CommonUI/src/Tests/Components/ErrorBoundary.test.tsx

ErrorBoundary As class component
In this pull request, we've made a crucial improvement to our error boundary implementation. The original error boundary was implemented as a functional component using a try...catch block, which had limitations in capturing errors thrown by child components.
In addition to the refactoring, we've included thorough test cases to ensure the reliability of the error boundary.

Rewrites ErrorBoundary as class Component to catch errors

---

CommonUI/src/Components/Dictionary/DictionaryOfStrings.tsx
CommonUI/src/Tests/Components/DictionaryOfStrings.test.tsx
CommonUI/src/Tests/Components/SideMenuItem.test.tsx

Added tests for SideMenuItem and DictionaryOfStrings components
Added test cases for SideMenuItem and DictionaryOfStrings components in Common UI

Added tests for SideMenuItem and DictionaryOfStrings components

---

CommonServer/Middleware/BearerTokenAuthorization.ts
CommonServer/Tests/Middleware/BearerTokenAuthorization.test.ts

Bearer token auth test

---

Common/Tests/Types/Database/Date.test.ts

Add Test cases for Common/Database/Date

---

.eslintrc.json

add eslint object-curly-spacing rule

---

CommonServer/Tests/Middleware/NotificationMiddleware.test.ts
CommonServer/Tests/Utils/Cookie.test.ts

Tests for notification middleware and cookie utils
Added test cases for NotificatoinMiddleware and CookieUtil files

Tests for notification middleware and cookie utils

---

CommonUI/src/Components/Loader/Loader.tsx
CommonUI/src/Components/Modal/Modal.tsx
CommonUI/src/Tests/Components/Modal.test.tsx
CommonUI/src/Tests/Components/Tabs.test.tsx

Tests for Tabs and Modal components
- Added tests for CommonUI/Tabs
- Added tests for CommonUI/Modal
- Added missing test ids

Added tests for Tabs and Modal components

---

CommonServer/Tests/Utils/CronTab.test.ts
CommonServer/Tests/Utils/JsonToCsv.test.ts
CommonServer/Utils/CronTab.ts

Added tests for JsonToCsv and CronTab utils functions
- added tests for JsonToCsv util function
- added tests for CronTab util funtion
- handled errors for getNextExecutionTime

Added tests for JsonToCsv and CronTab util functions

---

CommonServer/Tests/API/BaseAPI.test.ts
CommonServer/Tests/API/ProbeAPI.test.ts
CommonServer/Tests/API/helpers.ts

Hi. Open for suggestions and fixes

BaseAPI.test.tsx

---

CommonUI/src/Tests/Components/FilePicker.test.tsx

test: add coverage for FilePicker.ts

---

Model/Models/StatusPageGroup.ts

Fix Plan Group Update Error
If you created groups before the update, you can no longer delete or edit them.

Fix Plan Group Update Error

---

Model/Models/StatusPageAnnouncement.ts

Make announcement deletable.
Since the new plan update you cannot delete your announcement

Make announcement deletable

---

Model/Models/IncidentState.ts
Model/Models/Label.ts
Model/Models/MonitorStatus.ts
Model/Models/ScheduledMaintenanceState.ts
Model/Models/Team.ts
Model/Models/TeamPermission.ts

Everything you see should be deletable
I have granted permission for every "feature" with the read property on "Free" to delete it.

Everything you see should be deletable

---

CommonServer/Tests/Middleware/ProjectAuthorization.test.ts
CommonServer/Tests/Services/ProbeService.test.ts
CommonServer/Tests/Utils/AnalyticsDatabase/StatementGenerator.test.ts
CommonServer/Utils/AnalyticsDatabase/StatementGenerator.ts

Escape Analytics Database SQL
Escape SQL values sent to the Analytics Database, to prevent SQL injection attacks.
- [ x] Please make sure all jobs pass before requesting a review. 
- [ x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [x ] Have you lint your code locally before submission?
- [ x] Did you write tests where appropriate?

Escape Analytics Database SQL

---

CommonServer/Tests/API/ProjectAPI.test.ts
CommonServer/Tests/API/UserSmsApi.test.ts
CommonUI/jest.config.json
CommonUI/setupTest.js
CommonUI/src/Components/ComponentLoader/ComponentLoader.tsx
CommonUI/src/Components/List/List.tsx
CommonUI/src/Components/Pagination/Pagination.tsx
CommonUI/src/Tests/Components/List.test.tsx
CommonUI/src/Tests/Components/Pagination.test.tsx

- CommonServer/Tests/API/ProjectAPI.test.ts
- CommonServer/Tests/API/UserSmsApi.test.ts
- CommonUI/src/Tests/Components/Pagination.test.tsx
- CommonUI/src/Tests/Components/List.test.tsx
- CommonUI/src/Components/ComponentLoader/ComponentLoader.tsx
- CommonUI/src/Components/Pagination/Pagination.tsx
- CommonUI/src/Components/List/List.tsx
- CommonUI/jest.config.json
- CommonUI/setupTest.js

Add unit test for CommonServer and CommonUi

---

Common/Types/Date.ts
Common/Types/Events/EventInterval.ts
Common/Types/OnCallDutyPolicy/Layer.ts
CommonUI/package-lock.json
CommonUI/src/Components/Forms/BasicForm.tsx
CommonUI/src/Tests/Components/BasicForm.test.tsx
Dashboard/src/Components/OnCallPolicy/OnCallScheduleLayer/Layer.tsx
Dashboard/src/Components/OnCallPolicy/OnCallScheduleLayer/LayerPreview.tsx
Dashboard/src/Pages/OnCallDuty/SideMenu.tsx

layerUsers prop to LayerPreview component

Add useState hook to Layer component and pass

---

Workflow/Docs/ComponentDocumentation/JavaScript.md

Just a small typo for documentation

chore: Update typo in Javascript Code component's document in Workflow

---

Dashboard/src/Pages/Monitor/View/Interval.tsx
Dashboard/src/Pages/Monitor/View/Settings.tsx

fix: update monitor wrong breadcrumbs

---

CommonServer/EnvironmentConfig.ts
Dashboard/src/Pages/StatusPages/View/CustomHtmlCss.tsx

fix: update status page html css page breadcrump

---

Dashboard/src/Pages/Workflow/View/Index.tsx
Dashboard/src/Pages/Workflow/View/Variable.tsx

fix: update wrong workflow breadcrumbs

---

Dashboard/src/Pages/OnCallDuty/OnCallDutyPolicy/Escalation.tsx
Dashboard/src/Pages/OnCallDuty/OnCallDutySchedule/Layers.tsx

fix: update on-call duty wrong breadcrumbs

---

Dashboard/src/Components/Monitor/MonitorTable.tsx

Enhancement: optional description #894
Made the description on monitor page optional
Also checked the flow by adding a test monitor without description and it's successfully added.
https://github.com/OneUptime/oneuptime/assets/83939820/54d945db-e4cb-4dcb-b83c-3be6c1d71222

Made description optional

---

App/Index.ts
CommonServer/Utils/Telemetry.ts
CommonServer/package-lock.json
CommonServer/package.json

Update dependencies and remove unnecessary code

---

App/FeatureSet/Workers/DataMigrations/AddAttributesColumnToSpanAndLog.ts
App/FeatureSet/Workers/DataMigrations/Index.ts
Common/AnalyticsModels/CommonModel.ts
Common/Types/JSONFunctions.ts
CommonServer/Services/AnalyticsDatabaseService.ts
CommonServer/Utils/AnalyticsDatabase/StatementGenerator.ts
CommonUI/src/Components/Detail/Detail.tsx
CommonUI/src/Components/LogsViewer/LogItem.tsx
Dashboard/src/Components/LogsViewer/LogsViewer.tsx
Ingestor/API/OTelIngest.ts
Ingestor/Service/OTelIngest.ts
Model/AnalyticsModels/Log.ts
Model/AnalyticsModels/Span.ts

Attributes

---

App/FeatureSet/Docs/Static/scripts/infrastructure-agent/install-linux.sh
Common/Types/ArrayUtil.ts
Common/Types/Monitor/CriteriaFilter.ts
Common/Types/Monitor/ServerMonitor/ServerMonitorResponse.ts
CommonServer/Utils/Probe/Criteria/ServerMonitorCriteria.ts
Dashboard/src/Pages/StatusPages/View/Domains.tsx
Dashboard/src/Utils/Form/Monitor/CriteriaFilter.ts
InfrastructureAgent/Index.ts
InfrastructureAgent/Jobs/MonitorInfrastructure.ts
InfrastructureAgent/Types/ServerMonitorResponse.ts
InfrastructureAgent/Utils/ServerProcess.ts
InfrastructureAgent/package-lock.json
InfrastructureAgent/package.json

Process infra

---

.vscode/launch.json
Common/Types/IsolatedVM/ReturnResult.ts
Common/Types/JSONFunctions.ts
CommonServer/Types/Workflow/Components/Conditions/IfElse.ts
CommonServer/Types/Workflow/Components/JavaScript.ts
CommonServer/Utils/Probe/ProbeMonitorResponse.ts
CommonServer/Utils/VM.ts
CommonServer/package-lock.json
CommonServer/package.json
HelmChart/Public/oneuptime/templates/isolated-vm.yaml
IsolatedVM/API/VM.ts
IsolatedVM/Index.ts
IsolatedVM/Utils/VM.ts
IsolatedVM/package-lock.json
IsolatedVM/package.json
Nginx/default.conf.template
docker-compose.base.yml

Isolated vm

---

CommonServer/Utils/StartServer.ts
CommonServer/Utils/Telemetry.ts
Ingestor/API/OTelIngest.ts

Error spans

---

Nginx/default.conf.template

Refactor Tab component to include countBadge and tabType properties

---

Scripts/Install/LetsEncrypt/certs-issue.sh
Scripts/Install/LetsEncrypt/certs-renew.sh

Update nginx service name and host variable in cert helper scripts
- changed nginx service name from nginx to ingress
- changed domain variable name to host

Update nginx service name and host variable in cert helper scripts

---

App/FeatureSet/Workers/DataMigrations/AddEndDateToMonitorStatusTimelineWhereEndDateIsMissing.ts
App/FeatureSet/Workers/DataMigrations/Index.ts
CommonServer/Services/MonitorStatusTimelineService.ts
InfrastructureAgent/.goreleaser.yaml

chore: Add mutex lock and release for MonitorStatusTimeline creation

---

CommonUI/src/Components/EventItem/EventItem.tsx

This code change refactors the EventItem component to improve the display of event descriptions and labels. It updates the CSS classes for the event descriptions to enhance readability and adds CSS classes for the event labels to improve their styling. This enhancement improves the overall appearance and user experience of the EventItem component.

refactor: Improve event item descriptions and labels

---

App/FeatureSet/Docs/Content/telemetry/open-telemetry.md

Remove duplicate "Swift" entry
basically, Swift entry was duplicated in the OpenTelemetry docs so it's removed.
N/A
N/A

Remove duplicate "Swift" entry

---

Tests/Scripts/endpoint-status.sh

Included the -L option in the curl command, ensuring that it will follow any 301 redirects until the final URL is reached.

Update endpoint-status.sh to follow redirects

---

App/FeatureSet/Docs/Utils/Nav.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/Docs/Utils/Nav.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/Docs/Utils/Nav.ts

---

App/FeatureSet/ApiReference/Service/PageNotFound.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/PageNotFound.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/PageNotFound.ts

---

App/FeatureSet/Docs/Utils/Render.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/Docs/Utils/Render.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/Docs/Utils/Render.ts

---

App/FeatureSet/ApiReference/Service/Introduction.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Introduction.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Introduction.ts

---

App/FeatureSet/ApiReference/Service/Status.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Status.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Status.ts

---

App/FeatureSet/ApiReference/Service/Permissions.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Permissions.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Permissions.ts

---

App/FeatureSet/ApiReference/Service/Pagination.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Pagination.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Pagination.ts

---

App/FeatureSet/ApiReference/Service/Model.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Model.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Model.ts

---

App/FeatureSet/ApiReference/Utils/Resources.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Utils/Resources.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Utils/Resources.ts

---

App/FeatureSet/ApiReference/Service/Errors.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Errors.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Errors.ts

---

App/FeatureSet/ApiReference/Service/Authentication.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Service/Authentication.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Service/Authentication.ts

---

App/FeatureSet/ApiReference/Index.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/ApiReference/Index.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/ApiReference/Index.ts

---

App/Index.ts

OneUptime Copilot: Improve Comments on /App/Index.ts

[OneUptime Copilot] Improve Comments on /App/Index.ts

---

App/FeatureSet/Docs/Index.ts

OneUptime Copilot: Improve Comments on /App/FeatureSet/Docs/Index.ts

[OneUptime Copilot] Improve Comments on /App/FeatureSet/Docs/Index.ts

---

HelmChart/Public/oneuptime/templates/_helpers.tpl
HelmChart/Public/oneuptime/values.yaml

- added `imagePullSecrets` to the chart for cases with private/proxy docker registries
- added commented examle in the `values.yaml` file
- deleted extra whitespaces (yaml linter)

Add imagePullSecrets to chart

---

Common/Types/BrandColors.ts
Common/UI/Components/Charts/Line/LineChart.tsx
Dashboard/src/Components/Monitor/MonitorCharts/MonitorChart.tsx

Make graphs beautiful

---

App/FeatureSet/Workers/Index.ts
Common/Server/Infrastructure/Queue.ts
Common/package-lock.json
Common/package.json

feat: Add Bull Board for monitoring and managing queues

---

Dashboard/src/Routes/OnCallDutyRoutes.tsx

feat: Add lazy loading for OnCallDutyPolicyViewLogsView component

---

App/FeatureSet/Workers/Utils/Cron.ts

Improved comments on /App/FeatureSet/Workers/Utils/Cron.ts

Improved comments on /App/FeatureSet/Workers/Utils/Cron.ts

---

App/FeatureSet/ApiReference/Service/Status.ts

Improved comments on /App/FeatureSet/ApiReference/Service/Status.ts

Improved comments on /App/FeatureSet/ApiReference/Service/Status.ts

---

App/FeatureSet/Workers/DataMigrations/AddMonitoringDatesToMonitors.ts

Improved comments on /App/FeatureSet/Workers/DataMigrations/AddMonitoringDatesToMonitors.ts

Improved comments on /App/FeatureSet/Workers/DataMigrations/AddMonitoringDatesToMonitors.ts

---

App/FeatureSet/Home/Static/js/switchUrl.js

Improved comments on /App/FeatureSet/Home/Static/js/switchUrl.js

Improved comments on /App/FeatureSet/Home/Static/js/switchUrl.js

---

App/FeatureSet/Workers/Jobs/MonitorMetrics/MonitorMetricsByMinute.ts

Improved comments on /App/FeatureSet/Workers/Jobs/MonitorMetrics/MonitorMetricsByMinute.ts

Improved comments on /App/FeatureSet/Workers/Jobs/MonitorMetrics/MonitorMetricsByMinute.ts

---

App/FeatureSet/Workers/DataMigrations/AddAttributesColumnToSpanAndLog.ts

Improved comments on /App/FeatureSet/Workers/DataMigrations/AddAttributesColumnToSpanAndLog.ts

Improved comments on /App/FeatureSet/Workers/DataMigrations/AddAttributesColumnToSpanAndLog.ts

---

App/FeatureSet/Workers/Index.ts
App/FeatureSet/Workers/Jobs/OnCallDutyPolicyExecutionLog/ExecutePendingExecutions.ts
App/FeatureSet/Workers/Jobs/ScheduledMaintenance/ScheduleRecurringEvents.ts
App/FeatureSet/Workers/Jobs/ScheduledMaintenance/SendSubscriberRemindersOnEventScheduled.ts
Common/Models/DatabaseModels/ScheduledMaintenance.ts
Common/Models/DatabaseModels/ScheduledMaintenanceTemplate.ts
Common/Server/Infrastructure/Postgres/SchemaMigrations/1725975175669-MigrationName.ts
Common/Server/Infrastructure/Postgres/SchemaMigrations/1725976810107-MigrationName.ts
Common/Server/Infrastructure/Postgres/SchemaMigrations/Index.ts
Common/Server/Services/IncidentService.ts
Common/Server/Services/IncidentStateService.ts
Common/Server/Services/ScheduledMaintenanceService.ts
Common/Types/Database/DatabaseProperty.ts
Common/Types/Events/Recurring.ts
Common/Types/SerializableObjectDictionary.ts
Common/UI/Components/Events/RecurringArrayFieldElement.tsx
Common/UI/Components/Events/RecurringArrayViewElement.tsx
Common/UI/Components/Events/RecurringViewElement.tsx
Dashboard/src/Components/ScheduledMaintenance/ScheduledMaintenanceTable.tsx
Dashboard/src/Pages/ScheduledMaintenanceEvents/View/Index.tsx
Dashboard/src/Pages/Settings/ScheduledMaintenanceTemplateView.tsx
Dashboard/src/Pages/Settings/ScheduledMaintenanceTemplates.tsx

Stop execution on incident ack

---

HelmChart/Public/oneuptime/templates/ingress.yaml

Wrap Host with Quote so we can have wildcard domain

---

HelmChart/Public/oneuptime/templates/secrets.yaml

Just making all the secret of the Helm chart compatible with stringData instead of data
No related issue

Refactor changing secret values from data to stringData

---

HelmChart/Public/oneuptime/README.md
HelmChart/Public/oneuptime/templates/_helpers.tpl
HelmChart/Public/oneuptime/templates/accounts.yaml
HelmChart/Public/oneuptime/templates/admin-dashboard.yaml
HelmChart/Public/oneuptime/templates/api-reference.yaml
HelmChart/Public/oneuptime/templates/app.yaml
HelmChart/Public/oneuptime/templates/dashboard.yaml
HelmChart/Public/oneuptime/templates/docs.yaml
HelmChart/Public/oneuptime/templates/fluent-ingest.yaml
HelmChart/Public/oneuptime/templates/haraka.yaml
HelmChart/Public/oneuptime/templates/home.yaml
HelmChart/Public/oneuptime/templates/incoming-request-ingest.yaml
HelmChart/Public/oneuptime/templates/isolated-vm.yaml
HelmChart/Public/oneuptime/templates/nginx.yaml
HelmChart/Public/oneuptime/templates/open-telemetry-ingest.yaml
HelmChart/Public/oneuptime/templates/otel-collector.yaml
HelmChart/Public/oneuptime/templates/probe-ingest.yaml
HelmChart/Public/oneuptime/templates/probe.yaml
HelmChart/Public/oneuptime/templates/server-monitor-ingest.yaml
HelmChart/Public/oneuptime/templates/status-page.yaml
HelmChart/Public/oneuptime/templates/test-server.yaml
HelmChart/Public/oneuptime/templates/worker.yaml
HelmChart/Public/oneuptime/templates/workflow.yaml
HelmChart/Public/oneuptime/values.yaml

Pod resources and probes additional containers
Added the option to apply pod resources to all of the project components
Added the option to add additional containers to the probes pods to enable VPN side-car containers such as Tailscale.

Helm chart pod resources and probes additional containers

---

Docs/Content/monitor/custom-code-monitor.md

Add where to find monitor logs

---

Common/Models/DatabaseModels/StatusPageAnnouncement.ts
Common/Models/DatabaseModels/StatusPageAnnouncementTemplate.ts
Common/Server/API/StatusPageAPI.ts
Common/Server/Infrastructure/Postgres/SchemaMigrations/1757423505855-MigrationName.ts
Common/Server/Infrastructure/Postgres/SchemaMigrations/Index.ts
Common/Server/Services/StatusPageSubscriberService.ts
Dashboard/src/Pages/Settings/StatusPageAnnouncementTemplateView.tsx
Dashboard/src/Pages/Settings/StatusPageAnnouncementTemplates.tsx
Dashboard/src/Pages/StatusPages/AnnouncementCreate.tsx
Dashboard/src/Pages/StatusPages/AnnouncementView.tsx
StatusPage/src/Pages/Announcement/Detail.tsx
StatusPage/src/Pages/Announcement/List.tsx
StatusPage/src/Pages/Overview/Overview.tsx
Worker/Jobs/Announcement/SendNotificationToSubscribers.ts

Announcement monitor
