docker-compose.base.yml

Use docker network instead of exposing all ports manually
Currently, the ports of all service components are exposed manually through the docker compose file. This is unnecessary, since only the nginx proxy and the services between each other need to communicate.

Use docker network instead of exposing all ports manually

---

docker-compose.yml

Add docker network to docker-compose.yml
The network appears to not be carried of docker-compose.yml from the docker-compose.base.yml. This causes an error because of the missing network.

Add docker network to docker-compose.yml

---

StatusPage/src/Components/NavBar/NavBar.tsx

use overflow-x-scroll to stop nav bar from operlapping on mobile dashboard
On mobile, x overflow for the dashboard nav bar is not defined. Because of that, the navbar element will be extending over the screen.
#451 
With this fix:
Without the fix:

use overflow-x-scroll to stop nav bar from operlapping on mobile dashboard

---

.eslintrc.json

added no unneeded ternary in eslint

---

CommonUI/jest.config.json
CommonUI/src/Tests/Components/ComponentsModal.test.tsx

- Adds test coverage for `ComponentsModal.tsx` (100%)
- Adds LCOV as a reporter (though `/coverage` is ignored). This is useful to combine it with [Coverage Gutters VS](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) code extension to see the coverage

chore: add ComponentsModal.tsx test coverage

---

CommonUI/src/Components/EventItem/EventItem.tsx

Affected resources exceed width in status page
The affected resources exceed the width of the status page when there are too many of them

Fix affected resources overflow

---

CommonUI/src/Components/Forms/ModelForm.tsx

While exploring the dashboard with its features I noticed the loading state in ModelForm when I tried to create something new like Incident, Monitor, etc. I opened the developer tools to Inspect the Network calls and saw a bunch of API calls that were duplicated.
The ModelForm accepts props `fields`, an array of form fields.  Looks like there's a duplicate calls for `setFormFields` function. The first one is `useAsyncEffect` for the component mount life cycle and another `useAsyncEffect` for `props.fields` changes.
I removed the first since the `setFormFields` only makes sense when `props.fields` value has been passed to the component or changed.

fix: duplicate api call in ModelForm

---

CommonUI/src/Components/Dropdown/Dropdown.tsx

For the dropdown component, when the component is focused the border color is the default color of react-select which is inconsistent with our primary color. Also the option of the dropdown selected background color and option hover (focus) background color don't match the primary color.

fix: Update Dropdown (react-select) style

---

CommonServer/API/BaseAnalyticsAPI.ts
CommonServer/Services/AnalyticsDatabaseService.ts
CommonServer/Tests/Services/AnalyticsDatabaseService.test.ts
CommonServer/Tests/Utils/AnalyticsDatabase/Statement.test.ts
CommonServer/Tests/Utils/AnalyticsDatabase/StatementGenerator.test.ts
CommonServer/Types/AnalyticsDatabase/DeleteBy.ts
CommonServer/Types/AnalyticsDatabase/DeleteOneBy.ts
CommonServer/Types/AnalyticsDatabase/UpdateBy.ts
CommonServer/Types/AnalyticsDatabase/UpdateOneBy.ts
CommonServer/Utils/AnalyticsDatabase/Statement.ts
CommonServer/Utils/AnalyticsDatabase/StatementGenerator.ts

Refactor Analytics SQL generation to use query params
SQL is generated using the Statement class which guards
against accidental SQL injection using a special "SQL"
template literal tag.
INSERT functionality is not using the new Statement class
pending resolution of Nested column type functionality.

Refactor Analytics SQL generation to use query params

---

CommonUI/src/Components/Workflow/RunModal.tsx

close #963 
After:
https://github.com/OneUptime/oneuptime/assets/20983608/9f169c80-8817-4b84-a9c8-0cd84591b5cc

fix: workflow crash on manually run

---

CommonUI/src/Components/Navbar/NavBarItem.tsx
CommonUI/src/Utils/Navigation.ts
Dashboard/src/Components/NavBar/NavBar.tsx
StatusPage/src/Components/NavBar/NavBar.tsx

If you look at the navigation bar (header) of the dashboard and you navigate around pages. Example: Monitors page, there are 4 levels: All, Inoperational, Disabled, and Monitor Detail View. You will notice that NavBarItem is only in active state if it's in All Page which is a props `route` pass to the component.
The NavBarItem should be in the active state even if we navigate around the `monitors` page.
- `../monitors`
- `../monitors/:id`
- `../monitors/inoperational`
- `../monitors/disabled`
Conceptually, any route starts with `../minitors`, the NavbarItem should be in the active state.
https://github.com/OneUptime/oneuptime/assets/20983608/3cf85d87-3d45-4a58-8879-ad471d50292a
https://github.com/OneUptime/oneuptime/assets/20983608/6ad08b05-e5a2-4c12-bb92-f45ba57c71ae

fix: NavbarItem is active only for the specific route

---

Dashboard/src/Utils/RouteMap.ts

There's a missing route path for that page so it renders schedule maintenance page by default and cause API to get the wrong params for projectId and cause the error.

fix: schedule ongoing error

---

CommonServer/Services/DatabaseService.ts
CommonServer/Tests/Services/ScheduledMaintenanceService.test.ts
CommonServer/Tests/TestingUtils/Services/ScheduledMaintenanceServiceHelper.ts
CommonServer/Tests/TestingUtils/Services/ScheduledMaintenanceStateServiceHelper.ts

@koroglumert reported multiple workflow triggers with a single state change. Upon investigation, there are at least two code paths independently triggering workflows for the same change to `currentScheduledMaintenanceStateId`.
1. `changeScheduledMaintenanceState` in ScheduledMaintenanceService.ts https://github.com/OneUptime/oneuptime/blob/64e0d3e7fa803a6e961bbbcc4ed97ac4ec61fa8c/CommonServer/Services/ScheduledMaintenanceService.ts#L424-L428
1. `onCreateSuccess` in ScheduledMaintenanceStateTimelineService.ts https://github.com/OneUptime/oneuptime/blob/64e0d3e7fa803a6e961bbbcc4ed97ac4ec61fa8c/CommonServer/Services/ScheduledMaintenanceStateTimelineService.ts#L128-L135
In addition, the same error is reported to also happen to the "On Update Incident" trigger. Therefore, there may be quite a …

Fix accidental workflow triggering

---

CommonServer/Tests/Services/TeamMemberService.test.ts

`TeamMemberService.test.ts` contains flaky tests. The flakiness can be observed in both #1251 and #1252. Tests in both PRs fail, yet the failed tests have nothing to do with the code changes. I cannot reproduce the failed tests locally.
Upon investigation, the cause seems to be the slowness of GitHub Action runners, leading to tests exceeding Jest's default 5-second-long timeout.
This PR increases the test timeout to 60 seconds for `TeamMemberService.test.ts`.
https://github.com/OneUptime/oneuptime/pull/1254#issuecomment-1999121156
N/A

Fix flaky tests

---

CommonServer/Tests/Services/TeamMemberService.test.ts
CommonUI/src/Components/Breadcrumbs/Breadcrumbs.tsx
CommonUI/src/Components/Link/Link.tsx
CommonUI/src/Tests/Components/Breadcrumbs.test.tsx
Dashboard/src/Components/Workflow/WorkflowElement.tsx
Dashboard/src/Pages/Workflow/View/Settings.tsx
Dashboard/src/Pages/Workflow/Workflows.tsx
Dashboard/src/Utils/RouteMap.ts

The cause for #1252 is incorrect paths. Instead of the correct path `dashboard/some-uuid/workflows/workflow/another-uuid`, an incorrect path of `dashboard/some-uuid/workflows/workflow` is being used.
Upon investigation, the path generation algorithm is naive - breaking up `pathname` by `/` and assigning a portion of `pathname` based on the array index. https://github.com/OneUptime/oneuptime/blob/b8fcc4c40c071b68545fa902e06297a63e23c647/CommonUI/src/Utils/Navigation.ts#L41-L44
In addition, readers with a keen eye would've noticed that Workflow routes do not follow the convention set by other routes such as Incidents. Workflow routes have an additional `/workflow` in its path. Thus Workflow routes break the assumption made by the path generation algorithm.
Lastly, self links are widely …

Fix workflow breadcrumbs and avoid self links

---

CommonUI/src/Components/ModelTable/BaseModelTable.tsx

Button disabled state render incorrectly
When click on filter button in monitors page, It cannot click any header button such as refresh or close filter bar. so normally it should be disable only data fetching or loading.

fix: setting header buttons in BaseModelTable

---

App/FeatureSet/Docs/Content/installation/docker-compose.md

This PR is a small change to the documentation when installing OneUptime via docker compose without NPM.
It's preferrable to export the env variables in a subshell because otherwise certain variables such as `COMPOSE_PROJECT_NAME` will remain in the current shell, causing conflicts with other compose projects for the duration of the session.
For example, after installing OneUptime, I went to go bring up my GitLab compose project and it started using `oneuptime` as the project name based on the exported `COMPOSE_PROJECT_NAME` variable.
This had a series of negative consequences:
- The docker network was now `oneuptime_default` instead of `gitlab_default`
- All named volumes were switched from `gitlab_volume-name` to `oneuptime_volume-name`.
Afterwards, GitLab was unable to be reached via …

docs: export env variables in a subshell

---

HelmChart/Public/oneuptime/README.md
HelmChart/Public/oneuptime/templates/_helpers.tpl
HelmChart/Public/oneuptime/values.yaml

Configure ENCRYPTION_SECRET and ONEUPTIME_SECRET with external secrets instead plain text values in _values_ file Helm chart
Add configuration in the `_helpers.tpl` file of the Helm chart to configure some secrets using external secrets, instead plain text values in _values_ file.
https://github.com/OneUptime/oneuptime/issues/1675

Add option to configure ENCRYPTION_SECRET and ONEUPTIME_SECRET using external secrets

---

HelmChart/Public/oneuptime/templates/secrets.yaml

Fix Helm Chart Deployment Fails when using External Clickhouse
According to issue #1713, the following error occurs when using an external clickhouse:
`Error from server (BadRequest): error when creating "secret.yaml": Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 8.` 
Unfortunately I could not determine the root cause of the issue—please leave a comment if you know why this happens. Even doing some debug the generated yaml was with the right value. However I was able to get rid of the error by replacing the base64-encoded `data` to a plain-text `stringData`, which lets k8s take care of the base64 encoding and maintains the same level of obfuscation.
closes #1713

Fix externalClickhouse password secret

---

HelmChart/Public/oneuptime/templates/api-reference.yaml
HelmChart/Public/oneuptime/templates/docs.yaml
HelmChart/Public/oneuptime/templates/home.yaml
HelmChart/Public/oneuptime/templates/ingestor.yaml
HelmChart/Public/oneuptime/templates/nginx.yaml
HelmChart/Public/oneuptime/templates/workflow.yaml
HelmChart/Public/oneuptime/values.yaml

Added startupProbe to deployments with healthchecks, replacing initialDelaySeconds.
Additionally made startup probes configurable (periodSeconds and failureThreshold can be set in values.yaml), and added a fallback to initialDelaySeconds if startup probes are disabled.

Add startupProbe to deployments with healthchecks

---

Dashboard/src/Components/Alert/Alert.tsx

Fix route on Alert name link in list of alerts
originally clicking the alert name would attempt to open an incident page for the alert's ID - resulting in an error page being shown

Fix alert name links opening invalid/broken page

---

configure.sh

Improve the configure.sh script
The script was not working on alpine, that we are using, so while debugging it, I decided to improve it a bit

refactor: modernize configure.sh

---

HelmChart/Public/oneuptime/templates/nginx.yaml
HelmChart/Public/oneuptime/values.yaml
Nginx/default.conf.template
docker-compose.base.yml

All OneUptime's services are now ipv6 friendly except Nginx that still listen only on IPv4. This PR finish the work done on #1773 and #1807.
This PR allow to modify nginx's listen address and options to be able to listen on dual and ipv6 only network stack.
It introduce the `NGINX_LISTEN_ADDRESS` and `NGINX_LISTEN_OPTIONS` environmental variable inside the nginx configuration template so modify both parameter.
This PR don't change the current behaviors.
IPv6 only:
```env
NGINX_LISTEN_ADDRESS=[::]:
NGINX_LISTEN_OPTIONS=
```
dual stack:
```env
NGINX_LISTEN_ADDRESS=[::]:
NGINX_LISTEN_OPTIONS=ipv6only=off
```
#1348
#1773
#1807

Feature: Nginx: Allow to specify listen options

---

Common/Server/Services/IncidentService.ts

In some instances, database ORM is returning a string instead of a number. This commit ensures that a number is returned by this function.
Fix Incident Number Concatenating instead of incrementing
Simple fix to ensure that function is returning a number instead of a string
No related issue raised, direct fix as similar to issue #1854

Fix Incident Number Concatenating instead of incrementing

---

Nginx/Jobs/WriteCustomCertsToDisk.ts

This pull request includes a small but important change to the `WriteCustomCertsToDisk` job in the `Nginx/Jobs/WriteCustomCertsToDisk.ts` file. The change updates the file paths used when writing custom certificates to disk to use `cert.fullDomain` instead of `cert.domain`.
* [`Nginx/Jobs/WriteCustomCertsToDisk.ts`](diffhunk://#diff-b92bdb33e5d129d5f1c9f0182ee3c6e4b18100be36d2aea4b9351edb7a06ef81L61-R66): Updated file paths for writing `.crt` and `.key` files to use `cert.fullDomain` for better accuracy and consistency

Fix undefined as domain name when saving custom SSL-Certs

---

OTelCollector/Dockerfile.tpl

When otel-collector runs with runAsNonRoot: true and a specific runAsUser UID, gomplate can't write to /etc. Change the output path to /tmp to avoid permission issues

Fix permission issues if otel-collector runs as non root

---

HelmChart/Public/oneuptime/templates/_helpers.tpl
HelmChart/Public/oneuptime/templates/api-reference.yaml
HelmChart/Public/oneuptime/templates/app.yaml
HelmChart/Public/oneuptime/templates/docs.yaml
HelmChart/Public/oneuptime/templates/fluent-ingest.yaml
HelmChart/Public/oneuptime/templates/home.yaml
HelmChart/Public/oneuptime/templates/incoming-request-ingest.yaml
HelmChart/Public/oneuptime/templates/isolated-vm.yaml
HelmChart/Public/oneuptime/templates/nginx.yaml
HelmChart/Public/oneuptime/templates/open-telemetry-ingest.yaml
HelmChart/Public/oneuptime/templates/otel-collector.yaml
HelmChart/Public/oneuptime/templates/probe-ingest.yaml
HelmChart/Public/oneuptime/templates/probe.yaml
HelmChart/Public/oneuptime/templates/server-monitor-ingest.yaml
HelmChart/Public/oneuptime/templates/worker.yaml
HelmChart/Public/oneuptime/templates/workflow.yaml

In the Helm chart, when autoscaling.enabled = true is set in values.yaml, a HorizontalPodAutoscaler takes care of managing the number of replicas. For this reason, the replicas field should be omitted in the Deployment to avoid it being reset to 1 on every helm upgrade

Exclude parameter "replicas" in Deployments, if autoscaling.enabled = true

---

Common/Tests/Server/API/BaseAPI.test.ts

I've updated the Jest mock for 'Common/Server/EnvironmentConfig' in 'Common/Tests/Server/API/BaseAPI.test.ts' to include 'LogLevel' and 'ConfigLogLevel'. This resolves a TypeError (Cannot read properties of undefined (reading 'INFO')) that occurred when the logger was invoked during test execution.
The error was caused by an incomplete mock that did not provide the logging configuration, leading to a crash in 'Logger.getLogLevel()'.
Additionally, I've added 'DisableTelemetry: true' to the mock to prevent unnecessary telemetry initialization during these specific API tests.

Fix(tests): Correct EnvironmentConfig mock in BaseAPI.test.ts

---

Docs/Content/api-reference/API Reference.md
Docs/Utils/Nav.ts

This commit introduces a new "API Reference" section in the documentation navigation.
- A new navigation group "API Reference" is added to `Docs/Utils/Nav.ts`.
- This group links to a new page `/docs/api-reference/api-reference`.
- The new page `Docs/Content/api-reference/API Reference.md` is created and contains a link to the main OneUptime API Reference at `/reference`.

feat: Add API Reference link to documentation

---

Scripts/TerraformProvider/Core/TerraformProviderGenerator.ts
Scripts/TerraformProvider/GenerateProvider.ts

chore(ci): [terraform] Add darwin/arm Build Target
The Terraform provider wasn't releasing with a `darwin/arm` target, so you couldn't use it on Apple Silicon Macs. This adds that target to the build process.
Was originally over at OneUptime/terraform-provider-oneuptime#1 but didn't realize that this is the place to put it!
N/A

chore(ci): [terraform] Add darwin/arm Build Target

---

Scripts/TerraformProvider/Core/TerraformProviderGenerator.ts
Scripts/TerraformProvider/GenerateProvider.ts

chore(ci): [terraform] Add Missing arm64 Targets
A previous commit added `arm` targets, which is 32-bit ARM. We also need `arm64` targets (64-bit ARM.)
This commit also adds `arm`/`arm64` for other `GOOS` targets.
#1967 was originally meant to do this.
N/A

chore(ci): [terraform] Add Missing arm64 Targets
